<?php

namespace AppBundle\Repository;

/**
 * AbstractServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractServerRepository extends \Doctrine\ORM\EntityRepository
{
}
